lib/Transforms/Scalar/PlaceSafepoints.cpp, test/CodeGen/X86/statepoint-frameescape.ll
llvm.frameescape() intrinsic is not a real call.
The intrinsic can only exist in the entry block.
Inserting a gc.statepoint() before llvm.frameescape() may split the
entry block, and push the intrinsic out of the entry block.
=> Don't Place Entry Safepoints Before the llvm.frameescape() Intrinsic

include/llvm/ADT/Triple.h, lib/Support/Triple.cpp, lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp, lib/Target/X86/X86FrameLowering.cpp, lib/Target/X86/X86FrameLowering.h, lib/Target/X86/X86ISelLowering.cpp, lib/Target/X86/X86Subtarget.h, lib/Target/X86/X86TargetMachine.cpp
Add the notion of a CoreCLR environment and use it to drive a different expansion of alloca.
Still much left undone: the actual inline probe sequence, handling the case where the probe is needed in the prolog, x86 support, non-windows support, and optimizations when we know we're going to be zeroing the allocated memory.
=> Initial workup for alloca and inline stack probes for CoreCLR.

include/llvm/CodeGen/ISDOpcodes.h, include/llvm/IR/Intrinsics.td, include/llvm/IR/Statepoint.h, lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp, lib/CodeGen/SelectionDAG/SelectionDAGDumper.cpp, lib/CodeGen/SelectionDAG/StatepointLowering.cpp, lib/IR/Statepoint.cpp, lib/IR/Verifier.cpp, lib/Target/X86/X86ISelLowering.cpp, lib/Target/X86/X86ISelLowering.h, lib/Transforms/Scalar/RewriteStatepointsForGC.cpp, test/CodeGen/X86/transition-call-lowering.ll, test/Transforms/RewriteStatepointsForGC/transition.ll
This intrinsic may be used to support calls from functions that are
GC-aware ("managed functions") to functions that are not GC-aware
("unmanaged functions"). This intrinsic is similar to the existing
statepoint instruction, except that it offers the backend the
opportunity to insert (somewhat) arbitrary code to managed the
transition from managed code to unmanaged code and back.
In order to support the injection of transition code, this intrinsic
wraps the STATEPOINT DAG node generated by the usual statepoint
lowering with two additional nodes: GC_TRANSITION_START and
GC_TRANSITION_END. The intrinsic accepts an additional set of
parameters that are supplied as operands to these nodes that may
be used by the backend during code generation.
=> Add an intrinsic for calls that are GC transitions.

lib/CodeGen/SelectionDAG/StatepointLowering.cpp, lib/Target/X86/X86CallingConv.td, lib/Target/X86/X86ISelDAGToDAG.cpp, lib/Target/X86/X86ISelLowering.cpp, lib/Target/X86/X86ISelLowering.h, lib/Target/X86/X86InstrCompiler.td, lib/Target/X86/X86MCInstLower.cpp, lib/Target/X86/X86RegisterInfo.cpp, lib/Target/X86/X86RegisterInfo.h
Lowering is split between ISel and Emit. The pieces that do not need to
introduce new control flow are handled during the former phase; the rest
are handled during the latter. New pseudo-opcodes are added to the X86
target for those operations that must be deferred to Emit.
=> Lower GC_TRANSITION_{START,END} for CoreCLR on x86-64.

lib/Target/X86/X86ISelLowering.cpp
This is only valid in functions that use ebp or rbp as the frame pointer.
=> Support @llvm.read_register("ebp"|"rbp").

lib/Target/X86/X86FrameLowering.cpp, lib/Target/X86/X86FrameLowering.h, lib/Target/X86/X86ISelLowering.cpp
This provides an inline expansion for the within-method locallocs for managed code. Prior to this we'd just adjust the stack pointer and hope for the best. Now we do the requisite page touches to ensure the stack grows the way the OS expects.
The inline instruction sequence is essentially the same as the __chkstk helper in the CRT save that virtual registers are used instead of R10 and R11.
=> Expansion for the inline stack probe.

lib/Target/X86/X86CallingConv.td, lib/Target/X86/X86ISelDAGToDAG.cpp, lib/Target/X86/X86ISelLowering.cpp, lib/Target/X86/X86RegisterInfo.cpp, lib/Target/X86/X86RegisterInfo.h
The GC pause helper uses the C calling convention, but also saves
registers that may contain return values. Add the appropriate
regmask to the call instruction to keep the register allocator from
using registers that might be clobbered by the call.
=> Fix the GC pause calling convention.

lib/Target/X86/X86ISelLowering.cpp, lib/Transforms/Scalar/RewriteStatepointsForGC.cpp, test/CodeGen/X86/statepoint-frameescape.ll, test/CodeGen/X86/transition-call-lowering.ll
The LLVM tests found two bugs in GC-related code:
- The flag that directs the statepoint rewriter not to track base pointers
was not being properly initialized
- STATEPOINT nodes preceeded by GC_TRANSITION_RA nodes were not being
properly rewritten
The test run is clean with these fixes.
=> Fix two GC-related bugs.

lib/Target/X86/X86FrameLowering.cpp, lib/Target/X86/X86FrameLowering.h, lib/Target/X86/X86ISelLowering.cpp
This change enables use of the inline stack probe within the method prolog, for cases where the local frame size exceeds 4096 bytes. The existing alloca code is extended to handle the prolog case by allowing precoloring of the various virtual registers to RCX and RDX, saving/restoring RCX/RDX around the entire probe sequence. For now the save/restore is done via push/pop; if this proves to be not viable long term we can try and get them into the caller-supplied save area.
Upstream frame-gen logic is generalized to handle the case where the in-prolog check creates control flow and hence changes the "current" basic block. Responsibilty for marking the added MachineInstrs as frame setup is moved to the expansions themselves.
=> Implement the prolog inline stack probe.

include/llvm/Analysis/LibCallSemantics.h, include/llvm/CodeGen/FunctionLoweringInfo.h, include/llvm/CodeGen/MachineModuleInfo.h, lib/Analysis/LibCallSemantics.cpp, lib/CodeGen/AsmPrinter/WinException.cpp, lib/CodeGen/AsmPrinter/WinException.h, lib/CodeGen/MachineModuleInfo.cpp, lib/CodeGen/SelectionDAG/FunctionLoweringInfo.cpp, lib/CodeGen/WinEHPrepare.cpp, lib/MC/MCWin64EH.cpp, lib/Transforms/InstCombine/InstructionCombining.cpp
This is a PR for changes going into the newly-created EH branch.  The purpose is to park the changes-so-far based on the soon-to-be-abandoned WinEH approach of using Itanium-style IR paired with funclet outlining in WinEHPrepare.  Support will be reworked when [the new IR representation](http://thread.gmane.org/gmane.comp.compilers.llvm.devel/85783) lands.  I'm going to shift focus to aspects of EH that are independent of the impending rewrite (e.g. filter function outlining).  Putting these changes here lets anyone curious see where things are/were heading and provide feedback, and lets me park similar changes dependent on this in the EH branch of LLILC.
=> Add CoreCLR personality function and EH table emission

lib/ExecutionEngine/RuntimeDyld/RuntimeDyld.cpp
A custom resolver now has an option of returning UINT64_MAX
from findSymbol to indicate that no relocations should be applied
for the symbol. This will be used by llilc as ngen jit.
This change was discussed with Lang Hames.
=> Allow clients to handle relocations for external symbols manually.

include/llvm/CodeGen/MachineModuleInfo.h, lib/CodeGen/AsmPrinter/AsmPrinter.cpp, lib/CodeGen/AsmPrinter/WinException.cpp, lib/CodeGen/MachineModuleInfo.cpp, lib/CodeGen/SelectionDAG/FunctionLoweringInfo.cpp, lib/CodeGen/WinEHPrepare.cpp
Expand HandlerTreeNode to have a ClauseKind (now that there are three) and
a FilterFunction used in filter handlers.
Change ClrEHClause to pass along a HandlerTreeNode opaquely rather than
replicating its fields.
Ensure that outlined filter handlers are inserted in the function list
just after the filters they handle.
Check in a few places that are determining whether to emit EH-relevant
info whether a function has a Win EH parent, so that early-outlined
filters are included.
=> Support CoreCLR filters

lib/Target/X86/X86CallingConv.h, lib/Target/X86/X86CallingConv.td
Modify CLR_SecretParameter calling convention
to make the secret parameter the first pointer-sized parameter
(still passed in R10) rather than a parameter passed with a
"CLR_SecretParameter" attribute.
=> SecretParam calling convention changes

include/llvm/ExecutionEngine/Orc/ObjectLinkingLayer.h
Rename two functions to adhere to LLVM convention.
This change is necessary for LLILC ccFomat to succeed.
I'll submit the patch to LLVM as well, but checking in here
because the change is (a) trivial to merge and (b) necessary
to keep the lab green.
=> Rename two functions for conformance

include/llvm/Target/TargetFrameLowering.h, lib/CodeGen/PrologEpilogInserter.cpp, lib/Target/X86/X86FrameLowering.cpp, lib/Target/X86/X86FrameLowering.h
The PrologEpilog inserted maintains a cached list of all
restore-blocks to which epilogs are emitted. This value is
cached before Prolog emission and used after Prolog emission.
Therefore, the list emitProlog() should maintain the list
unaltered.
During X86 Frame lowering, inline emission of
StackProbes for CoreCLR is currently done within the emitProlog()
step. This breaks the above invariant wrt restore blocks for
singe basic-block functions where the prolog block is also an
epilog block.
This change fixes this problem by:
1) Emitting a call to ChkStk_stub in the prolog (and thus not
splitting it)
2) Replaciong the stub with the actual inline sequence after
the prolog and all epilogs are emitted.
Fixes https://github.com/dotnet/llilc/issues/735
=> FrameLower: Inline StackProbe after Prolog/Epilog emission.

CMakeLists.txt, cmake/modules/CrossCompile.cmake
Cross-compilation uses recursive cmake invocations to build native host
tools.  These recursive invocations only forward a fixed set of
variables/options, since the native environment is generally the default.
This change adds -DLLVM_TARGET_IS_CROSSCOMPILE_HOST=TRUE to the recursive
cmake invocations, so that cmake files can distinguish these recursive
invocations from top-level ones, which can explain why expected options
are unset.
LLILC will use this to avoid trying to generate its build rules in the
crosscompile native host target (where it is not needed), which would fail
if attempted because LLILC requires a cmake variable passed on the command
line, which is not forwarded in the recursive invocation.
=> Flag recursive cmake invocations for cross-compile

include/llvm/ADT/SmallBitVector.h
Closes #85.
File llvm/include/llvm/ADT/SmallBitVector.h has the following code:
```
template<bool AddBits, bool InvertMask>
void applyMask(const uint32_t *Mask, unsigned MaskWords) {
if (NumBaseBits == 64 && MaskWords >= 2) {
uint64_t M = Mask[0] | (uint64_t(Mask[1]) << 32);
if (InvertMask) M = ~M;
if (AddBits) setSmallBits(getSmallBits() | M);
else         setSmallBits(getSmallBits() & ~M);
} else {
uint32_t M = Mask[0];
if (InvertMask) M = ~M;
if (AddBits) setSmallBits(getSmallBits() | M);
else         setSmallBits(getSmallBits() & ~M);
}
}
```
When compiled for a 64 bit target the Microsoft C++ compiler emits
a warning:
```
.../SmallBitVector.h(565): warning C4319: '~': zero extending 'uint32_t' to 'uintptr_t' of greater size
```
The line referred to is the one containing the last …
=> Fix to remove Visual C++ warning C4319 from SmallBitVector.h

include/llvm/Transforms/Scalar.h, lib/Transforms/Scalar/RewriteStatepointsForGC.cpp, test/Transforms/RewriteStatepointsForGC/base-pointers-12.ll
This change modifies RewriteStatepointsForGC to:
1) Re-introduces the base-pointer computation and reporting
logic for CoreCLR.
~ Removes the exclusion for CoreCLR only checked in to MS branch.
No change to LLVM Mainline.
~ Base-pointers are necessary to report Exterior pointers.
1) Handle gc-pointers generated by casts.
~ This includes stack locations, globals, and any other
unmanaged value cast to a managed pointer.
~ The cast instruction is considered as the birth of the GC pointer.
2) Not report pointers that cannot be relocated
~ global, local, and constant pointers
=> ReWriteStatepointsForGC: Handle Managed pointers

include/llvm/CodeGen/FunctionLoweringInfo.h, include/llvm/CodeGen/MachineModuleInfo.h, include/llvm/CodeGen/WinEHFuncInfo.h, lib/CodeGen/AsmPrinter/WinException.cpp, lib/CodeGen/AsmPrinter/WinException.h, lib/CodeGen/MachineModuleInfo.cpp, lib/CodeGen/SelectionDAG/FunctionLoweringInfo.cpp, lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp, lib/CodeGen/WinEHPrepare.cpp
This is a PR for a change to go into the EH branch.
I think the relevant bits are stable enough to upstream this to LLVM (assuming I can figure out how to write a lit test that verifies we generate tables as expected), but want to PR it into the EH branch first since this provides a more useful diff to review from the LLILC perspective.
I split it into one commit that adds the new functionality and a second that removes the old; the second is a straight revert of the relevant code to match master.
Note that consuming these tables in LLILC and passing them along to the CLR is still being implemented, though I've got far enough to vet that these tables are reasonable for basic cases.
Note also that EH table generation isn't the whole of EH lowering; funclet prolog sequences will need some …
=> Add CLR EH table generation for new EH; remove it for landingpad EH

include/llvm/Analysis/LibCallSemantics.h, lib/Analysis/LibCallSemantics.cpp, lib/MC/MCWin64EH.cpp
Now that LLILC processes relocations itself, there's no need to continue
suppressing the one that gets generated in .xdata for the pointer to the
personality function.
=> Undo CoreCLR xdata runtime_function nulling

lib/CodeGen/AsmPrinter/WinException.cpp, lib/CodeGen/WinEHPrepare.cpp, test/CodeGen/WinEH/wineh-coreclr.ll
- Need to close all pending clauses on funclet boundaries since clauses
can't span across funclets
- The bookkeeping when closing pending clauses wasn't quite right,
leading to redundant clause emission; fix that.
- Factor the logic to close pending clauses into a helper since it's a
bit more verbose and is needed in three places now.
- Don't put a sentinel at the base of HandlerStack; no need to keep a top
element that's redundant with PendingFoo locals.
- Only push pending on the stack and update start/state if we enter a
descendant of the current pending state.
=> Fix EH Clause computation

lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp, lib/Target/X86/X86CallingConv.h, lib/Target/X86/X86FrameLowering.cpp
Undo some formatting changes and remove one useless #include, to get rid of
some noise when diffing MS branch against master.
=> Revert cosmetic changes

lib/CodeGen/WinEHPrepare.cpp
This prevents the cloning from generating incorrect clones of debug info
metadata attached to the cloned IR.
=> Set NoModuleLevelChanges flag in funclet cloning

include/llvm/IR/Statepoint.h, lib/Transforms/Scalar/RewriteStatepointsForGC.cpp
This allows compilation to succeed with WinEH in LLILC, though dynamically
it would not produce correct behavior on exception paths.
Created #105 to track the need to replace the stubs with a real implementation; submitting this change here because I think it makes sense to hold off upstreaming until #105 is completed.
@swaroop-sridhar PTAL.
=> Stub out rewriting on exception paths for WinEH

lib/Target/X86/X86FrameLowering.cpp
This is a workaround to unblock LLILC until D13774 lands to fix the issue
upstream.  This change follows a pattern used in the Hexagon back-end and
in GC transition lowering in the MS branch.
=> Mark catchret targets address-taken

lib/CodeGen/AsmPrinter/AsmPrinter.cpp, lib/CodeGen/AsmPrinter/WinException.cpp, lib/CodeGen/AsmPrinter/WinException.h, lib/Target/X86/X86FrameLowering.cpp, lib/Target/X86/X86ISelLowering.cpp, lib/Target/X86/X86MCInstLower.cpp, test/CodeGen/X86/coreclr-pinvoke.ll, test/CodeGen/X86/late-address-taken.ll, test/CodeGen/X86/win-catchpad-csrs.ll, test/CodeGen/X86/win-catchpad-nested.ll, test/CodeGen/X86/win-catchpad.ll
This PR has two commits.  The first is just the change that's been approved to commit upstream in [D13774](http://reviews.llvm.org/D13774), rebased to the MS branch.  The second changes how address-taken-ness is handled in the lowering of GC transitions (which only exists in the MS branch).
The first commit is included because this seems like the best way to get that change to the MS branch; checking it in upstream and letting that flow down without the second change would break catchret lowering (because of some code in LowerMachineOperand that the MS branch has which does not exist upstream), and checking in the second change without the first would similarly break GC transition lowering.
The second commit is included to fix the issue with catchret lowering, and at the same time bring …
=> Update address-taken MBB handling

include/llvm/MC/MCELFStreamer.h, include/llvm/MC/MCObjectStreamer.h, include/llvm/MC/MCStreamer.h, lib/MC/MCAsmStreamer.cpp, lib/MC/MCELFStreamer.cpp, lib/MC/MCObjectStreamer.cpp, lib/MC/MCStreamer.cpp, lib/Target/AArch64/MCTargetDesc/AArch64ELFStreamer.cpp, lib/Target/ARM/MCTargetDesc/ARMELFStreamer.cpp, lib/Target/Mips/MCTargetDesc/MipsELFStreamer.cpp, lib/Target/Mips/MCTargetDesc/MipsELFStreamer.h
EmitValue assumes an absolute (non PC relative) fix-up only. This allows to create PC-relative fix-up optionally.
=> PC-relative support for EmitValue

lib/Target/X86/X86InstrCompiler.td
The machine verifier complains without this due to the store memopnd we
put on the instruction.
=> Annotate GC_TRANSITION_RA opcode as 'mayStore'

include/llvm/MC/MCStreamer.h, include/llvm/MC/MCWinCOFFStreamer.h, lib/MC/MCStreamer.cpp, lib/MC/WinCOFFStreamer.cpp
Extending MCWinCOFFStreamer to handle relcation in form of general .
This change is a prerequisite to CoreRT pdb data generation.
=> Extending MCWinCOFFStreamer to handle relcation in form of general expressions.
